export const CORE_VERSION = '0.1.0'

export * from './encoding/base32'
export * from './sync/chunks'
export * from './otp/hotp'
export * from './otp/totp'
export * from './otp/steam'
export * from './otp/yandex'
export * from './otp/entryCode'
export * from './otp/uri'
// R3：OTP 类型注册表。toOtpDigits 不在此导出——经 './import/normalize' re-export（保持既有导入面），
// 两处 `export *` 同名会触发 TS2308 重名冲突，故本模块用显式清单
export {
  TYPE_PROFILES,
  defaultDigitsFor,
  otpTypeForHost,
} from './otp/typeProfiles'
export type {
  TypeProfile,
  CodeComputeInput,
  CodeComputeResult,
} from './otp/typeProfiles'
export * from './model'
export * from './vault'
export * from './merge/vaultMerge'
export * from './merge/conflictStore'
export * from './storage/adapter'
export * from './storage/memory'
export * from './storage/vaultStore'
export * from './match/engine'
export * from './tags/filter'
export * from './crypto/aesgcm'
export * from './backup/envelope'
export * from './backup/policy'
export * from './backup/secretBag'
export * from './backup/sources'
export * from './backup/legacyCloudMigrate'
export * from './backup/autoRun'
export * from './backup/autoRunScheduler'
export * from './security/securityStore'
export * from './security/multiKek'
export * from './security/lockPolicy'
export * from './import/types'
export * from './import/conflict'
export * from './import/dedup'
export * from './import/normalize'
export * from './import/sniff'
export * from './import/generic'
export * from './import/schemes'
export * from './import/uriBatch'
export * from './import/aegis'
export * from './import/winauth'
export * from './import/jsonApps'
export * from './import/miscApps'
export * from './import/paste'
export * from './import/sqlite'
export * from './import/zipAes'
export * from './import/zipRead'
export * from './import/authenticatorPlus'
export * from './icons/registry'
export * from './cloud/canonical'
export * from './cloud/backend'
export * from './cloud/retention'
export * from './cloud/targetPath'
export * from './cloud/webdav'
export * from './cloud/gist'
export * from './cloud/s3'
export * from './cloud/gdrive'
export * from './cloud/onedrive'
export * from './cloud/syncOrchestrator'
export * from './cloud/syncState'
export * from './cloud/oauthRefresh'
export * from './cloud/multiTarget'
export * from './export/otpauthText'
export * from './export/aegisVault'
