// bump.mjs 自动化测试（杂-I5）：版本落点门禁此前零测试，拒绝正则、8 处落点、Cargo.lock
// 锚定全靠人工验证。此处以 mkdtemp 临时 fixture + 真实子进程（exit code / stdout/stderr
// 全走真实路径）覆盖：合法版本改写全部落点、prerelease 与非法格式拒绝、--check 失配报错、
// Cargo.lock 只动 totp-desktop 条目不动依赖。
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, describe, expect, it } from 'vitest'
import { fileURLToPath } from 'node:url'

const BUMP = fileURLToPath(new URL('./bump.mjs', import.meta.url))

// ---- fixture 构造：与仓库真实落点同构的最小文件集 ----

const BASE = '0.1.0'
const NEXT = '1.2.3'

const pkgJson = (v) => `{
  "name": "x",
  "version": "${v}",
  "private": true
}
`
const tauriConf = (v) => `{
  "$schema": "https://schema.tauri.app/config/2",
  "productName": "TOTP.Tools",
  "version": "${v}",
  "identifier": "com.example.totp"
}
`
const cargoToml = (v) => `[package]
name = "totp-desktop"
version = "${v}"
description = "TOTP desktop"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
`
// 依赖条目（serde）夹在 totp-desktop 之前，验证 name 锚定不误伤
const cargoLock = (v) => `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "totp-desktop"
version = "${v}"
dependencies = [
 "serde 1.0.200",
]
`
const coreIndex = (v) => `export const CORE_VERSION = '${v}'

export * from './encoding/base32'
`

/** 在临时目录铺出 bump 全部 8 落点（统一 version=initial，core index 例外可单独覆写） */
function makeFixture(initial = BASE) {
  const root = mkdtempSync(join(tmpdir(), 'totp-bump-test-'))
  const put = (rel, content) => {
    const p = join(root, rel)
    mkdirSync(join(p, '..'), { recursive: true })
    writeFileSync(p, content)
  }
  for (const rel of ['apps/desktop', 'apps/extension', 'packages/core', 'packages/ui']) {
    put(`${rel}/package.json`, pkgJson(initial))
  }
  put('apps/desktop/src-tauri/tauri.conf.json', tauriConf(initial))
  put('apps/desktop/src-tauri/Cargo.toml', cargoToml(initial))
  put('apps/desktop/src-tauri/Cargo.lock', cargoLock(initial))
  put('packages/core/src/index.ts', coreIndex(initial))
  return root
}

/** 以 BUMP_ROOT 指向 fixture 真实执行 bump.mjs（不经 spawn shell，Windows 同构） */
function runBump(root, args) {
  return execFileSync(process.execPath, [BUMP, ...args], {
    env: { ...process.env, BUMP_ROOT: root },
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })
}

function runBumpExpectFailure(root, args) {
  try {
    runBump(root, args)
  } catch (err) {
    return { status: err.status, stderr: String(err.stderr), stdout: String(err.stdout) }
  }
  throw new Error(`bump ${args.join(' ')} 应失败退出，实际 exit 0`)
}

const readAll = (root) => ({
  desktop: JSON.parse(readFileSync(join(root, 'apps/desktop/package.json'), 'utf8')).version,
  extension: JSON.parse(readFileSync(join(root, 'apps/extension/package.json'), 'utf8')).version,
  tauriConf: JSON.parse(readFileSync(join(root, 'apps/desktop/src-tauri/tauri.conf.json'), 'utf8')).version,
  corePkg: JSON.parse(readFileSync(join(root, 'packages/core/package.json'), 'utf8')).version,
  uiPkg: JSON.parse(readFileSync(join(root, 'packages/ui/package.json'), 'utf8')).version,
  cargoToml: readFileSync(join(root, 'apps/desktop/src-tauri/Cargo.toml'), 'utf8').match(/^version = "(.*)"/m)?.[1],
  lock: readFileSync(join(root, 'apps/desktop/src-tauri/Cargo.lock'), 'utf8'),
  coreIndex: readFileSync(join(root, 'packages/core/src/index.ts'), 'utf8'),
})

const tmpRoots = []
afterAll(() => { for (const r of tmpRoots) rmSync(r, { recursive: true, force: true }) })

describe('bump 合法版本：改写全部 8 处落点', () => {
  it('pnpm bump 1.2.3 → 5 JSON + Cargo.toml + Cargo.lock(totp-desktop) + CORE_VERSION 全部落到 1.2.3', () => {
    const root = makeFixture()
    tmpRoots.push(root)
    const out = runBump(root, [NEXT])
    const v = readAll(root)
    expect(v.desktop).toBe(NEXT)
    expect(v.extension).toBe(NEXT)
    expect(v.tauriConf).toBe(NEXT)
    expect(v.corePkg).toBe(NEXT)
    expect(v.uiPkg).toBe(NEXT)
    expect(v.cargoToml).toBe(NEXT)
    expect(v.coreIndex).toContain(`CORE_VERSION = '${NEXT}'`)
    // 文本就地改写，格式不重排
    expect(v.coreIndex).toBe(coreIndex(BASE).replace(`'${BASE}'`, `'${NEXT}'`))
    // Cargo.lock：totp-desktop 条目改写，依赖条目（serde）不动
    expect(v.lock).toContain(`name = "totp-desktop"\nversion = "${NEXT}"`)
    expect(v.lock).toContain('name = "serde"\nversion = "1.0.200"')
    expect(out).toContain(`packages/core/src/index.ts (CORE_VERSION) → ${NEXT}`)
  })

  it('已一致时幂等（重复 bump 同版本 exit 0，无输出改动）', () => {
    const root = makeFixture(NEXT)
    tmpRoots.push(root)
    runBump(root, [NEXT])
    const v = readAll(root)
    expect(v.desktop).toBe(NEXT)
    expect(v.lock).toContain(`name = "totp-desktop"\nversion = "${NEXT}"`)
  })
})

describe('bump 拒绝路径：prerelease 后缀与非法格式', () => {
  it.each([
    ['1.2.3-beta.1'],
    ['1.2.3-rc.1+build'],
    ['abc'],
    ['1.2'],
    ['v1.2.3'],
  ])('bump %s → exit 非 0，全部落点保持原版本', (bad) => {
    const root = makeFixture()
    tmpRoots.push(root)
    const r = runBumpExpectFailure(root, [bad])
    expect(r.status).toBe(2)
    expect(r.stderr).toContain('仅接受纯数字')
    const v = readAll(root)
    expect(v.desktop).toBe(BASE)
    expect(v.cargoToml).toBe(BASE)
    expect(v.lock).toContain(`name = "totp-desktop"\nversion = "${BASE}"`)
    expect(v.coreIndex).toContain(`CORE_VERSION = '${BASE}'`)
  })

  it('缺版本参数且未带 --check → exit 2 用法提示', () => {
    const root = makeFixture()
    tmpRoots.push(root)
    const r = runBumpExpectFailure(root, [])
    expect(r.status).toBe(2)
  })
})

describe('bump --check：失配报错 / 匹配通过', () => {
  it('全落点一致 → exit 0', () => {
    const root = makeFixture(NEXT)
    tmpRoots.push(root)
    // --check 不带版本参数：以 apps/desktop/package.json 当前版本为基准
    const out = runBump(root, ['--check'])
    expect(out).toBe('')
    expect(readAll(root).coreIndex).toContain(`CORE_VERSION = '${NEXT}'`)
  })

  it('落点漂移（ui package.json 旧版）→ exit 非 0 且指名文件', () => {
    const root = makeFixture(NEXT)
    tmpRoots.push(root)
    writeFileSync(join(root, 'packages/ui/package.json'), pkgJson(BASE))
    const r = runBumpExpectFailure(root, ['--check'])
    expect(r.status).toBe(1)
    expect(r.stderr).toContain('packages/ui/package.json')
    expect(r.stderr).toContain(`期望 ${NEXT}`)
  })

  it('CORE_VERSION 游离漂移（杂-I4 场景）→ --check 报错拦截', () => {
    const root = makeFixture(NEXT)
    tmpRoots.push(root)
    writeFileSync(join(root, 'packages/core/src/index.ts'), coreIndex(BASE))
    const r = runBumpExpectFailure(root, ['--check'])
    expect(r.status).toBe(1)
    expect(r.stderr).toContain('packages/core/src/index.ts')
    expect(r.stderr).toContain('CORE_VERSION')
  })

  it('Cargo.lock 缺 totp-desktop 条目 → exit 非 0', () => {
    const root = makeFixture()
    tmpRoots.push(root)
    writeFileSync(join(root, 'apps/desktop/src-tauri/Cargo.lock'), cargoLock(BASE).replace(/\[\[package\]\]\nname = "totp-desktop"\nversion = "[^"]*"\ndependencies = \[\n "serde 1\.0\.200",\n\]/, ''))
    const r = runBumpExpectFailure(root, ['--check'])
    expect(r.status).toBe(1)
    expect(r.stderr).toContain('未找到 totp-desktop 包条目')
  })
})
